/* Generated By:JJTree: Do not edit this line. ASTAdjective.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAdjective extends SimpleNode {
  public ASTAdjective(int id) {
    super(id);
  }

  public ASTAdjective(Parser p, int id) {
    super(p, id);
  }


  // Here is the code that was inserted by the script annotateAST.pl:

  //--------------------------------------------------------------

  // Manually added portion follows:
  String lexem = "";

  public void setLexem( String lex ) { lexem = lex; }
  public String getLexem() { return lexem; }

  // Override superclass handling:
  public String toString() { return super.toString()+ " : " + lexem; }

  //--------------------------------------------------------------

}
/* JavaCC - OriginalChecksum=4bc36b4b199441f244ee082621e3ad8d (do not edit this line) */
