/* Generated By:JJTree: Do not edit this line. ASTCompoundNoun.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCompoundNoun extends SimpleNode {
  public ASTCompoundNoun(int id) {
    super(id);
  }

  public ASTCompoundNoun(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7a5eef9d52bb8ad1e7fdcd28b257bfdd (do not edit this line) */
