/* Generated By:JJTree: Do not edit this line. ASTDeterminer.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDeterminer extends SimpleNode {
  public ASTDeterminer(int id) {
    super(id);
  }

  public ASTDeterminer(Parser p, int id) {
    super(p, id);
  }


  // Here is the code that was inserted by the script annotateAST.pl:

  //--------------------------------------------------------------

  // Manually added portion follows:
  String lexem = "";

  public void setLexem( String lex ) { lexem = lex; }
  public String getLexem() { return lexem; }

  // Override superclass handling:
  public String toString() { return super.toString()+ " : " + lexem; }

  //--------------------------------------------------------------

}
/* JavaCC - OriginalChecksum=10111da2ace90d4d25e0bdd4a182a0f3 (do not edit this line) */
