/* Generated By:JJTree: Do not edit this line. ASTNounPhrase.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNounPhrase extends SimpleNode {
  public ASTNounPhrase(int id) {
    super(id);
  }

  public ASTNounPhrase(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ef46543a5e5bc411eedbc887e6c89f48 (do not edit this line) */
