/* Generated By:JJTree: Do not edit this line. ASTPrepPhrase.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPrepPhrase extends SimpleNode {
  public ASTPrepPhrase(int id) {
    super(id);
  }

  public ASTPrepPhrase(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=797855c62866585caa9106919320a277 (do not edit this line) */
