/* Generated By:JJTree: Do not edit this line. ASTSentence.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSentence extends SimpleNode {
  public ASTSentence(int id) {
    super(id);
  }

  public ASTSentence(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c70ae0b13de4dd63dd23940ff11db100 (do not edit this line) */
