/* Generated By:JJTree: Do not edit this line. ASTSpeech.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSpeech extends SimpleNode {
  public ASTSpeech(int id) {
    super(id);
  }

  public ASTSpeech(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b8ac3b6bdb59c66f83ab76d42d113917 (do not edit this line) */
