/* Generated By:JJTree: Do not edit this line. ASTVerb.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVerb extends SimpleNode {
  public ASTVerb(int id) {
    super(id);
  }

  public ASTVerb(Parser p, int id) {
    super(p, id);
  }


  // Here is the code that was inserted by the script annotateAST.pl:

  //--------------------------------------------------------------

  // Manually added portion follows:
  String lexem = "";

  public void setLexem( String lex ) { lexem = lex; }
  public String getLexem() { return lexem; }

  // Override superclass handling:
  public String toString() { return super.toString()+ " : " + lexem; }

  //--------------------------------------------------------------

}
/* JavaCC - OriginalChecksum=204276eaeba2874a4f91fe3ae365a7d6 (do not edit this line) */
