/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 6;
  /** RegularExpression Id. */
  int DIGIT = 7;
  /** RegularExpression Id. */
  int DETERMINER = 8;
  /** RegularExpression Id. */
  int NOUN = 9;
  /** RegularExpression Id. */
  int PRONOUN = 10;
  /** RegularExpression Id. */
  int VERB = 11;
  /** RegularExpression Id. */
  int ADJ = 12;
  /** RegularExpression Id. */
  int PREPOSITION = 13;
  /** RegularExpression Id. */
  int WORD = 14;
  /** RegularExpression Id. */
  int LETTER = 15;
  /** RegularExpression Id. */
  int PERIOD = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<NUMBER>",
    "<DIGIT>",
    "<DETERMINER>",
    "<NOUN>",
    "<PRONOUN>",
    "<VERB>",
    "<ADJ>",
    "<PREPOSITION>",
    "<WORD>",
    "<LETTER>",
    "\".\"",
  };

}
