/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
public interface ParserTreeConstants
{
  public int JJTSPEECH = 0;
  public int JJTSENTENCE = 1;
  public int JJTNOUNPHRASE = 2;
  public int JJTCOMPOUNDNOUN = 3;
  public int JJTPREPPHRASE = 4;
  public int JJTVERBPHRASE = 5;
  public int JJTNOUN = 6;
  public int JJTPRONOUN = 7;
  public int JJTDETERMINER = 8;
  public int JJTADJECTIVE = 9;
  public int JJTPREPOSITION = 10;
  public int JJTVERB = 11;


  public String[] jjtNodeName = {
    "Speech",
    "Sentence",
    "NounPhrase",
    "CompoundNoun",
    "PrepPhrase",
    "VerbPhrase",
    "Noun",
    "Pronoun",
    "Determiner",
    "Adjective",
    "Preposition",
    "Verb",
  };
}
/* JavaCC - OriginalChecksum=f527a0219c604c4ebd53b562c2949e9d (do not edit this line) */
